### ISSUE TITLE
DatabaseRequestTracer StartAsync deprecated

### ISSUE THREAD

**Issue by lvermeulen** [Dynatrace/OneAgent-SDK-for-dotnet#19] opened 2020-10-02 14:48 UTC
How do I write an Entity Framework Core interceptor if I don't have StartAsync?

Right now I inherit from DbCommandInterceptor and override e.g.

```
        public override async Task<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand command, CommandEventData eventData, InterceptionResult<DbDataReader> result, CancellationToken cancellationToken = new CancellationToken())
        {
            await StartAsync(command).ConfigureAwait(false);
            return await base.ReaderExecutingAsync(command, eventData, result, cancellationToken).ConfigureAwait(false);
        }

        public override async Task<DbDataReader> ReaderExecutedAsync(DbCommand command, CommandExecutedEventData eventData, DbDataReader result, CancellationToken cancellationToken = new CancellationToken())
        {
            var reader = await base.ReaderExecutedAsync(command, eventData, result, cancellationToken).ConfigureAwait(false);
            Stop(command);

            return reader;
        }
```

How do I do that when StartAsync() has disappeared?

**Comment by Oberon00** [comment] 2020-10-02 16:44
I think this is a duplicate of #16. Please see the discussion there. The recommended way is to use `TraceAsync`  instead.

**Comment by lvermeulen** [comment] 2020-10-03 07:37
I'm not sure this is a duplicate. I'm looking for guidance, basically.

**Comment by z1c0** [comment] 2020-10-05 12:23
Hi @lvermeulen,

as @Oberon00 suggested using `TraceAsync` is the recommended way to go.

In your case, you can e.g. `await` a `Task` in `TraceAsync` that's started in `ReaderExecutingAsync` and gets finished in `ReaderExecutedAsync`.
If you don't have a `Task` provided by EF available for that, you can synchronize "manually" (see e.g. https://stackoverflow.com/questions/18756354/wrapping-manualresetevent-as-awaitable-task).

**Closed** 2021-06-03 08:08 UTC
